export const AUTH_API_BASE_URL = import.meta.env.VITE_AUTH_API_BASE_URL;
export const AUTH_API_LOGIN_URL = import.meta.env.VITE_AUTH_API_BASE_URL + '/auth/login';
export const PLAN_WS_URL = import.meta.env.VITE_PLANS_WS_URL;
export const ACCOUNTING_API_BASE_URL = import.meta.env.VITE_ACCOUNTING_API_BASE_URL;
export const ACCOUNTING_API_GET_PlANS_URL = import.meta.env.VITE_ACCOUNTING_API_GET_PlANS_URL;
export const ACCOUNTING_API_GET_OFFERS_URL = import.meta.env.VITE_ACCOUNTING_API_GET_OFFERS_URL;
export const ACCOUNTING_API_GET_INVOICES_URL = import.meta.env.VITE_ACCOUNTING_API_GET_INVOICES_URL;
export const ACCOUNTING_API_POST_INVOICES_URL = import.meta.env.VITE_ACCOUNTING_API_POST_INVOICES_URL;