#!/bin/sh
required_vars="VITE_AUTH_API_BASE_URL VITE_PLANS_WS_URL VITE_ACCOUNTING_API_BASE_URL VITE_ACCOUNTING_API_GET_OFFERS_URL VITE_ACCOUNTING_API_GET_INVOICES_URL VITE_ACCOUNTING_API_POST_INVOICES_URL VITE_ACCOUNTING_API_GET_PlANS_URL VITE_PLANS_API_BASE_URL VITE_PLANS_API_GET_PLANS_URL VITE_BILLING_API_BASE_URL VITE_BILLING_API_BASE_GET_PLAN_PRICES_URL VITE_CRYPTO_CLOUD_BILLING_API VITE_CRYPTO_CLOUD_BILLING_API_CREATE_INVOICE_URL VITE_FREE_PLAN_BILLING_API VITE_FREE_PLAN_BILLING_BILLING_API_CREATE_INVOICE_URL"

for var in $required_vars; do
  eval "val=\$$var"
  if [ -z "$val" ]; then
    echo "Error: $var env variable must be set."
    exit 1
  fi
done

envsubst < /app/config.template.js > /app/build/config.js

exec "$@"
